language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - "echo \"POSTGRES_USERNAME=$POSTGRES_USERNAME\nPOSTGRES_PASSWORD=$POSTGRES_PASSWORD\nPOSTGRES_HOST=$POSTGRES_HOST\nPOSTGRES_DB=$POSTGRES_DB\nJWT_SECRET=$JWT_SECRET\nALLOW_REQUESTS_FROM_URL=$ALLOW_REQUESTS_FROM_URL\" >> .env"
  - docker --version # print the version for logging
  - docker build -t udagram-users .
  - docker tag udagram-users schavezfuentes/udagram-users:latest

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push schavezfuentes/udagram-users